workflows:
  build_and_test:
    name: Build and Test
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        ANDROID_KEYSTORE_BASE64: Encrypted
        ANDROID_KEYSTORE_PASSWORD: Encrypted
        ANDROID_KEY_PASSWORD: Encrypted
        KEY_ALIAS: Encrypted
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK (debug)
        script: |
          flutter build apk --debug
      - name: Build App Bundle (release)
        script: |
          flutter build appbundle --release
      - name: Build iOS (release)
        script: |
          flutter build ios --release
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your_email@example.com
        on_build_success: true
        on_build_failure: false
